/**
 * Scans downloaded_icons/ and generates src/cloud-icons-index.ts
 * mapping friendly slugs to relative file paths.
 *
 * Run: bun run src/generate-cloud-index.ts
 */
import { resolve, relative, basename } from 'path';

const root = resolve(import.meta.dir, '..');
const iconsDir = resolve(root, 'downloaded_icons');
const outFile = resolve(root, 'src', 'cloud-icons-index.ts');

const entries: Array<{ prefix: string; slug: string; relPath: string }> = [];

// --- AWS: scan 64px SVGs from Architecture-Service-Icons ---
const awsBase = resolve(iconsDir, 'aws', 'Architecture-Service-Icons_01302026');
const glob = new Bun.Glob('*/64/*_64.svg');
for await (const match of glob.scan({ cwd: awsBase })) {
  const file = basename(match); // e.g. Arch_AWS-Lambda_64.svg
  const serviceName = file
    .replace(/^Arch_/, '')
    .replace(/_64\.svg$/, ''); // e.g. AWS-Lambda, Amazon-Simple-Storage-Service

  // Primary slug: strip Amazon-/AWS- prefix, lowercase, keep hyphens
  const slug = serviceName
    .replace(/^(Amazon|AWS)-/, '')
    .toLowerCase();

  const relPath = `aws/Architecture-Service-Icons_01302026/${match}`;
  entries.push({ prefix: 'aws', slug, relPath });
}

// Add common aliases for AWS services
const awsAliases: Record<string, string> = {
  's3': 'simple-storage-service',
  's3-glacier': 'simple-storage-service-glacier',
  'ebs': 'elastic-block-store',
  'ecs': 'elastic-container-service',
  'ecr': 'elastic-container-registry',
  'eks': 'elastic-kubernetes-service',
  'elb': 'elastic-load-balancing',
  'efs': 'elastic-file-system',
  'eb': 'elastic-beanstalk',
  'vpc': 'virtual-private-cloud',
  'edr': 'elastic-disaster-recovery',
  'mwaa': 'managed-workflows-for-apache-airflow',
  'sns': 'simple-notification-service',
  'sqs': 'simple-queue-service',
  'ses': 'simple-email-service',
  'iam': 'identity-and-access-management',
  'kms': 'key-management-service',
  'waf': 'web-application-firewall',
  'msk': 'managed-streaming-for-apache-kafka',
};

// Resolve aliases: find the entry with the target slug, then add alias entry
const awsEntries = entries.filter(e => e.prefix === 'aws');
for (const [alias, target] of Object.entries(awsAliases)) {
  const found = awsEntries.find(e => e.slug === target);
  if (found) {
    entries.push({ prefix: 'aws', slug: alias, relPath: found.relPath });
  }
}

// --- GCP: scan category SVGs ---
const gcpBase = resolve(iconsDir, 'gcp', 'Category Icons');
const gcpGlob = new Bun.Glob('*/SVG/*.svg');
for await (const match of gcpGlob.scan({ cwd: gcpBase })) {
  // match: "Compute/SVG/Compute-512-color.svg"
  // slug from folder name
  const parts = match.split('/');
  const folderName = parts[0]; // "Compute", "AI _ Machine Learning", etc.
  const slug = folderName
    .replace(/ _ /g, '-')
    .replace(/ & /g, '-')
    .replace(/ /g, '-')
    .toLowerCase();

  const relPath = `gcp/Category Icons/${match}`;
  entries.push({ prefix: 'gcp', slug, relPath });
}

// GCP aliases
const gcpAliases: Record<string, string> = {
  'ai': 'ai-machine-learning',
  'ml': 'ai-machine-learning',
  'bi': 'business-intelligence',
  'gke': 'containers',
  'serverless': 'serverless-computing',
  'monitoring': 'observability',
  'security': 'security-identity',
  'devtools': 'developer-tools',
};
const gcpEntries = entries.filter(e => e.prefix === 'gcp');
for (const [alias, target] of Object.entries(gcpAliases)) {
  const found = gcpEntries.find(e => e.slug === target);
  if (found) {
    entries.push({ prefix: 'gcp', slug: alias, relPath: found.relPath });
  }
}

// --- Generate output ---
const lines: string[] = [
  '// Auto-generated by generate-cloud-index.ts — do not edit manually',
  '',
  'export const cloudIconIndex: Record<string, string> = {',
];

// Sort for deterministic output
entries.sort((a, b) => {
  if (a.prefix !== b.prefix) return a.prefix.localeCompare(b.prefix);
  return a.slug.localeCompare(b.slug);
});

for (const e of entries) {
  lines.push(`  '${e.prefix}:${e.slug}': '${e.relPath}',`);
}

lines.push('};');
lines.push('');

await Bun.write(outFile, lines.join('\n'));
console.log(`Written ${entries.length} entries to src/cloud-icons-index.ts`);
